
package mangement.panel;

import java.awt.Cursor;
import mangement.Admin_login;
import mangement.Donor_form;
import mangement.Home;
import mangement.Log_In;


public class Home_LogIn_panel extends javax.swing.JPanel {
    
    
    private Cursor cursor;

    /**
     * Creates new form LogIn_panel
     */
    public Home_LogIn_panel() {
        initComponents();
        cursor = new Cursor(Cursor.HAND_CURSOR);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        new_donar = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        donar = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        admin = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(0, 102, 102));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(0, 102, 102));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Blood Management System Log In Portal");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, 580, 80));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Admin.png"))); // NOI18N
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 180, 160, 160));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/New User.png"))); // NOI18N
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 180, 160, 160));

        jLabel5.setBackground(new java.awt.Color(0, 102, 102));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/User.png"))); // NOI18N
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 160, 170));

        new_donar.setBackground(new java.awt.Color(0, 102, 102));
        new_donar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        new_donar.setForeground(new java.awt.Color(255, 255, 255));
        new_donar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        new_donar.setText("New Donar");
        new_donar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                new_donarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                new_donarMouseEntered(evt);
            }
        });
        add(new_donar, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 320, 200, 60));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 420, -1, -1));
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 580, 20));

        donar.setBackground(new java.awt.Color(0, 102, 102));
        donar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        donar.setForeground(new java.awt.Color(255, 255, 255));
        donar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        donar.setText("Donar");
        donar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                donarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                donarMouseEntered(evt);
            }
        });
        add(donar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, 190, 60));
        add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 370, 90, 20));
        add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 370, 130, 20));

        admin.setBackground(new java.awt.Color(0, 102, 102));
        admin.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        admin.setForeground(new java.awt.Color(255, 255, 255));
        admin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        admin.setText("Admin");
        admin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adminMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                adminMouseEntered(evt);
            }
        });
        add(admin, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 320, 190, 60));
        add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 370, 90, 20));
    }// </editor-fold>//GEN-END:initComponents

    private void donarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_donarMouseEntered
        
        donar.setCursor(cursor);
    }//GEN-LAST:event_donarMouseEntered

    private void new_donarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_new_donarMouseEntered
        
        new_donar.setCursor(cursor);
    }//GEN-LAST:event_new_donarMouseEntered

    private void new_donarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_new_donarMouseClicked
        
        Donor_form newForm = new Donor_form();
        newForm.setVisible(true);
    }//GEN-LAST:event_new_donarMouseClicked

    private void adminMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminMouseEntered
        
        admin.setCursor(cursor);
    }//GEN-LAST:event_adminMouseEntered

    private void donarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_donarMouseClicked
        
        
        Log_In obj = new Log_In();
        obj.setVisible(true);
        
    }//GEN-LAST:event_donarMouseClicked

    private void adminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminMouseClicked
       
        Admin_login login = new Admin_login();
        login.setVisible(true);
    }//GEN-LAST:event_adminMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel admin;
    private javax.swing.JLabel donar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JLabel new_donar;
    // End of variables declaration//GEN-END:variables

}
