
package mangement.panel;

import java.awt.Color;
import java.awt.Cursor;
import java.awt.Image;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import mangement.Home;
import mangement.MySqlConnect;

public class Profile_panel extends javax.swing.JPanel {
    
    private Cursor cursor; 
    

    /**
     * Creates new form Profile_panel
     */
    public Profile_panel() {
        initComponents();

        this.setSize(920,460);
        location_of_donar.setWrapStyleWord(true);
        location_of_donar.setLineWrap(true);
        
        cursor = new Cursor(Cursor.HAND_CURSOR);
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        profilePhoto = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        bloodGroup = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        first_name = new javax.swing.JLabel();
        last_name = new javax.swing.JLabel();
        another_number = new javax.swing.JLabel();
        age_of_donar = new javax.swing.JLabel();
        male_female = new javax.swing.JLabel();
        show_profile = new javax.swing.JButton();
        phonenumber = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        location_of_donar = new javax.swing.JTextArea();

        jLabel7.setText("jLabel7");

        setBackground(new java.awt.Color(0, 102, 102));
        setForeground(new java.awt.Color(204, 255, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 17)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 255, 153));
        jLabel1.setText("First Name ");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 100, 52));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 17)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 255, 153));
        jLabel2.setText("Last Name ");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 110, 100, 52));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 17)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 255, 153));
        jLabel3.setText("Your Phone Number");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 180, 52));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 17)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 255, 153));
        jLabel4.setText("Contact Number ");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 210, 200, 52));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 17)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 255, 153));
        jLabel5.setText("Blood Group ");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 400, 110, 30));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 17)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 255, 153));
        jLabel6.setText("Age ");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 60, 52));

        profilePhoto.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        add(profilePhoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 150, 200, 186));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 17)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 255, 153));
        jLabel8.setText("Location ");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 80, 52));

        bloodGroup.setBackground(new java.awt.Color(0, 0, 0));
        bloodGroup.setFont(new java.awt.Font("Calibri", 1, 17)); // NOI18N
        bloodGroup.setForeground(new java.awt.Color(255, 255, 255));
        bloodGroup.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bloodGroup.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        add(bloodGroup, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 350, 120, 50));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 17)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(153, 255, 153));
        jLabel9.setText("Gender ");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 320, 70, 52));

        first_name.setBackground(new java.awt.Color(0, 0, 0));
        first_name.setFont(new java.awt.Font("Calibri", 1, 17)); // NOI18N
        first_name.setForeground(new java.awt.Color(255, 255, 255));
        first_name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        first_name.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        add(first_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 250, 40));

        last_name.setBackground(new java.awt.Color(0, 0, 0));
        last_name.setFont(new java.awt.Font("Calibri", 1, 17)); // NOI18N
        last_name.setForeground(new java.awt.Color(255, 255, 255));
        last_name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        last_name.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        add(last_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 160, 260, 40));

        another_number.setBackground(new java.awt.Color(0, 0, 0));
        another_number.setFont(new java.awt.Font("Calibri", 1, 17)); // NOI18N
        another_number.setForeground(new java.awt.Color(255, 255, 255));
        another_number.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        another_number.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        add(another_number, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 260, 220, 40));

        age_of_donar.setBackground(new java.awt.Color(0, 0, 0));
        age_of_donar.setFont(new java.awt.Font("Calibri", 1, 17)); // NOI18N
        age_of_donar.setForeground(new java.awt.Color(255, 255, 255));
        age_of_donar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        age_of_donar.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        add(age_of_donar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 250, 40));

        male_female.setBackground(new java.awt.Color(0, 0, 0));
        male_female.setFont(new java.awt.Font("Calibri", 1, 17)); // NOI18N
        male_female.setForeground(new java.awt.Color(255, 255, 255));
        male_female.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        male_female.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        add(male_female, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 370, 220, 40));

        show_profile.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        show_profile.setText("Show Profile ");
        show_profile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                show_profileMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                show_profileMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                show_profileMouseExited(evt);
            }
        });
        add(show_profile, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 30, 170, 40));

        phonenumber.setBackground(new java.awt.Color(0, 102, 102));
        phonenumber.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        phonenumber.setForeground(new java.awt.Color(255, 255, 255));
        phonenumber.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        phonenumber.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        phonenumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                phonenumberKeyPressed(evt);
            }
        });
        add(phonenumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, 270, 40));

        location_of_donar.setEditable(false);
        location_of_donar.setBackground(new java.awt.Color(0, 102, 102));
        location_of_donar.setColumns(20);
        location_of_donar.setFont(new java.awt.Font("Calibri", 1, 17)); // NOI18N
        location_of_donar.setForeground(new java.awt.Color(255, 255, 255));
        location_of_donar.setRows(5);
        location_of_donar.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        jScrollPane1.setViewportView(location_of_donar);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, 270, 90));
    }// </editor-fold>//GEN-END:initComponents

    private void show_profileMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_show_profileMouseEntered
        
        show_profile.setBackground(new Color(101, 79, 161));
        show_profile.setCursor(cursor);
    }//GEN-LAST:event_show_profileMouseEntered
    
    private boolean validateField(){
        
        if (phonenumber.getText().isEmpty()){
            
            JOptionPane.showMessageDialog(null, "Please enter your 12 digit number","Warning",JOptionPane.PLAIN_MESSAGE);
            
            return false;
        }
        
        return true;
    }
    
    private void show_profileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_show_profileMouseClicked
        
        if (validateField()){
        
            String username = phonenumber.getText();
        
        try{
            Connection conn = MySqlConnect.ConnectDB();
            String sql = "SELECT phoneNumber,firstName,lastName,age,anotherContactNumber,location, gender,bloodGroup FROM blood_management_system.donar_information WHERE phoneNumber= '"+phonenumber.getText()+"'";
            PreparedStatement pst = conn.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            
            String query = "SELECT * FROM blood_management_system.donar_information where phoneNumber = '"+phonenumber.getText()+"'";
            PreparedStatement profile = conn.prepareStatement(query);
            ResultSet result = profile.executeQuery();
            
            rs.next();
            
            if (username.equals(rs.getString("phoneNumber"))){
                
                String firstName = rs.getString("firstName");
                String lastName =  rs.getString("lastName");
                String Age = rs.getString("age");
                String anotherphone = rs.getString("anotherContactNumber");
                String address = rs.getString("location");
                String gender = rs.getString("gender");
                String bloodgroup = rs.getString("bloodGroup");
                
                first_name.setText(firstName);
                last_name.setText(lastName);
                age_of_donar.setText(Age);
                another_number.setText(anotherphone);
                location_of_donar.setText(address);
                male_female.setText(gender);
                bloodGroup.setText(bloodgroup);
                
                
            }
            
            if (result.next()){
                
                byte[] image = result.getBytes("profile_photo");
                ImageIcon icon = new ImageIcon(image);
                Image img = icon.getImage();
                Image profile_picture = img.getScaledInstance(profilePhoto.getWidth(), profilePhoto.getHeight(), Image.SCALE_SMOOTH);
                ImageIcon newImage = new ImageIcon(profile_picture);
                profilePhoto.setIcon(newImage);
            }
            
            conn.close();
  
        }catch(Exception e){
            
           JOptionPane.showMessageDialog(null, "Details not found","ERROR",JOptionPane.PLAIN_MESSAGE);
            
        }
        
      }
        
    }//GEN-LAST:event_show_profileMouseClicked

    private void show_profileMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_show_profileMouseExited
        
        show_profile.setBackground(new Color(240,240,240));
    }//GEN-LAST:event_show_profileMouseExited

    private void phonenumberKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_phonenumberKeyPressed
        
        if (evt.getKeyCode()==KeyEvent.VK_ENTER){
            
            if (validateField()){
        
            String username = phonenumber.getText();
        
        try{
            Connection conn = MySqlConnect.ConnectDB();
            String sql = "SELECT phoneNumber,firstName,lastName,age,anotherContactNumber,location, gender,bloodGroup FROM blood_management_system.donar_information WHERE phoneNumber= '"+phonenumber.getText()+"'";
            PreparedStatement pst = conn.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            
            String query = "SELECT * FROM blood_management_database.donar_information where phoneNumber = '"+phonenumber.getText()+"'";
            PreparedStatement profile = conn.prepareStatement(query);
            ResultSet result = profile.executeQuery();
            
            rs.next();
            
            if (username.equals(rs.getString("phoneNumber"))){
                
                String firstName = rs.getString("firstName");
                String lastName =  rs.getString("lastName");
                String Age = rs.getString("age");
                String anotherphone = rs.getString("anotherContactNumber");
                String address = rs.getString("location");
                String gender = rs.getString("gender");
                String bloodgroup = rs.getString("bloodGroup");
                
                first_name.setText(firstName);
                last_name.setText(lastName);
                age_of_donar.setText(Age);
                another_number.setText(anotherphone);
                location_of_donar.setText(address);
                male_female.setText(gender);
                bloodGroup.setText(bloodgroup);
                
                
            }
            
            if (result.next()){
                
                byte[] image = result.getBytes("profile_photo");
                ImageIcon icon = new ImageIcon(image);
                Image img = icon.getImage();
                Image profile_picture = img.getScaledInstance(profilePhoto.getWidth(), profilePhoto.getHeight(), Image.SCALE_SMOOTH);
                ImageIcon newImage = new ImageIcon(profile_picture);
                profilePhoto.setIcon(newImage);
            }
            
            conn.close();
  
        }catch(Exception e){
            
           JOptionPane.showMessageDialog(null, "Details not found","ERROR",JOptionPane.PLAIN_MESSAGE);
            
        }
        
      }
            
        }
    }//GEN-LAST:event_phonenumberKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel age_of_donar;
    private javax.swing.JLabel another_number;
    private javax.swing.JLabel bloodGroup;
    private javax.swing.JLabel first_name;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel last_name;
    private javax.swing.JTextArea location_of_donar;
    private javax.swing.JLabel male_female;
    private javax.swing.JTextField phonenumber;
    private javax.swing.JLabel profilePhoto;
    private javax.swing.JButton show_profile;
    // End of variables declaration//GEN-END:variables
}
