
package mangement;

import java.awt.Color;
import java.awt.Cursor;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import mangement.panelAdmin.AdminProfile_panel;
import mangement.panelAdmin.DeleteDonor_panel;
import mangement.panelAdmin.ShowDonor_panel;
import mangement.panelAdmin.ShowMessage_panel;
import mangement.panelAdmin.ShowVisitor_panel;

public class Admin extends javax.swing.JFrame {
    
    private Cursor hand_cursor;
    private ImageIcon icon;
    
    // All panel of this Admin frame
    
    AdminProfile_panel panel1 = new AdminProfile_panel();
    ShowDonor_panel panel2 = new ShowDonor_panel();
    DeleteDonor_panel panel3 = new DeleteDonor_panel();
    ShowVisitor_panel panel4 = new ShowVisitor_panel();
    ShowMessage_panel panel5 = new ShowMessage_panel();

    /**
     * Creates new form Admin
     */
    public Admin() {
        initComponents();
        

        this.setTitle("Profile");
        
        hand_cursor = new Cursor(Cursor.HAND_CURSOR);
        icon = new ImageIcon(getClass().getResource("Blood logo.png"));
        this.setIconImage(icon.getImage());
        
        // add Profile_panel to dynamicPanel of Admin Frame
        
        dynamicPanel.removeAll();
        dynamicPanel.add(panel1);
        dynamicPanel.repaint();
        dynamicPanel.revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        profile_panel = new javax.swing.JPanel();
        profile = new javax.swing.JLabel();
        showDonar_panel = new javax.swing.JPanel();
        show_donor = new javax.swing.JLabel();
        deleteDonar_panel = new javax.swing.JPanel();
        delete_donor = new javax.swing.JLabel();
        showVisitor_panel = new javax.swing.JPanel();
        show_visitor = new javax.swing.JLabel();
        showMessage_panel = new javax.swing.JPanel();
        show_message = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        close = new javax.swing.JLabel();
        minimize = new javax.swing.JLabel();
        dynamicPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        profile_panel.setBackground(new java.awt.Color(153, 0, 51));
        profile_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        profile.setFont(new java.awt.Font("Monospaced", 1, 16)); // NOI18N
        profile.setForeground(new java.awt.Color(255, 255, 255));
        profile.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        profile.setText("Profile ");
        profile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                profileMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                profileMouseEntered(evt);
            }
        });
        profile_panel.add(profile, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 38));

        jPanel3.add(profile_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, -1, 60));

        showDonar_panel.setBackground(new java.awt.Color(51, 51, 51));
        showDonar_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        show_donor.setFont(new java.awt.Font("Monospaced", 1, 16)); // NOI18N
        show_donor.setForeground(new java.awt.Color(255, 255, 255));
        show_donor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        show_donor.setText("Show Donor");
        show_donor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                show_donorMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                show_donorMouseEntered(evt);
            }
        });
        showDonar_panel.add(show_donor, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 38));

        jPanel3.add(showDonar_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, -1, 60));

        deleteDonar_panel.setBackground(new java.awt.Color(51, 51, 51));
        deleteDonar_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        delete_donor.setFont(new java.awt.Font("Monospaced", 1, 16)); // NOI18N
        delete_donor.setForeground(new java.awt.Color(255, 255, 255));
        delete_donor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        delete_donor.setText("Delete Donor");
        delete_donor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                delete_donorMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                delete_donorMouseEntered(evt);
            }
        });
        deleteDonar_panel.add(delete_donor, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 38));

        jPanel3.add(deleteDonar_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 0, -1, -1));

        showVisitor_panel.setBackground(new java.awt.Color(51, 51, 51));
        showVisitor_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        show_visitor.setFont(new java.awt.Font("Monospaced", 1, 16)); // NOI18N
        show_visitor.setForeground(new java.awt.Color(255, 255, 255));
        show_visitor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        show_visitor.setText("Show Visitor");
        show_visitor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                show_visitorMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                show_visitorMouseEntered(evt);
            }
        });
        showVisitor_panel.add(show_visitor, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 38));

        jPanel3.add(showVisitor_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 0, -1, -1));

        showMessage_panel.setBackground(new java.awt.Color(51, 51, 51));
        showMessage_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        show_message.setFont(new java.awt.Font("Monospaced", 1, 16)); // NOI18N
        show_message.setForeground(new java.awt.Color(255, 255, 255));
        show_message.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        show_message.setText("Show Message");
        show_message.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                show_messageMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                show_messageMouseEntered(evt);
            }
        });
        showMessage_panel.add(show_message, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 38));

        jPanel3.add(showMessage_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 0, -1, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 1100, 40));

        jPanel4.setBackground(new java.awt.Color(51, 0, 51));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        close.setBackground(new java.awt.Color(255, 255, 255));
        close.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/homeIcon/icons8_Cancel_20px.png"))); // NOI18N
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeMouseEntered(evt);
            }
        });
        jPanel4.add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 0, 40, 50));

        minimize.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        minimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/homeIcon/icons8_Minimize_Window_20px.png"))); // NOI18N
        minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                minimizeMouseEntered(evt);
            }
        });
        jPanel4.add(minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 0, 40, 50));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, -1));

        dynamicPanel.setLayout(new java.awt.CardLayout());
        getContentPane().add(dynamicPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 1100, 520));

        setSize(new java.awt.Dimension(1099, 610));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked

        int choice = JOptionPane.showConfirmDialog(null, "Are you sure to exit ?", "Close", JOptionPane.YES_NO_OPTION,JOptionPane.PLAIN_MESSAGE);

        if (choice==JOptionPane.YES_OPTION){

            dispose();      // close the window
        }

    }//GEN-LAST:event_closeMouseClicked

    private void closeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseEntered

        close.setToolTipText("close");
        close.setCursor(hand_cursor);

    }//GEN-LAST:event_closeMouseEntered

    private void minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseClicked

        this.setState(this.ICONIFIED);
    }//GEN-LAST:event_minimizeMouseClicked

    private void minimizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseEntered

        minimize.setToolTipText("minimize");
        minimize.setCursor(hand_cursor);
    }//GEN-LAST:event_minimizeMouseEntered

    private void profileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profileMouseClicked
        
        this.setTitle("Profile");
        
        // To change the background color of selected panels
       
        profile_panel.setBackground(new Color(153, 0, 51));
        
        showDonar_panel.setBackground(new Color(51, 51, 51));
        deleteDonar_panel.setBackground(new Color(51, 51, 51));
        showVisitor_panel.setBackground(new Color(51, 51, 51));
        showMessage_panel.setBackground(new Color(51, 51, 51));
        
        // add Profile_panel to dynamicPanel of Admin Frame
        
        dynamicPanel.removeAll();
        dynamicPanel.add(panel1);
        dynamicPanel.repaint();
        dynamicPanel.revalidate();
        
        
    }//GEN-LAST:event_profileMouseClicked

    private void profileMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profileMouseEntered
        
        profile.setCursor(hand_cursor);
    }//GEN-LAST:event_profileMouseEntered

    private void show_donorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_show_donorMouseClicked
        
        this.setTitle("Show Donor");
        
        // To change the background color of selected panels
       
        showDonar_panel.setBackground(new Color(153, 0, 51));
        
        profile_panel.setBackground(new Color(51, 51, 51));
        deleteDonar_panel.setBackground(new Color(51, 51, 51));
        showVisitor_panel.setBackground(new Color(51, 51, 51));
        showMessage_panel.setBackground(new Color(51, 51, 51));
        
        // add ShowDonar_panel to dynamicPanel of Admin Frame
        
        dynamicPanel.removeAll();
        dynamicPanel.add(panel2);
        dynamicPanel.repaint();
        dynamicPanel.revalidate();
    }//GEN-LAST:event_show_donorMouseClicked

    private void show_donorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_show_donorMouseEntered
       
        show_donor.setCursor(hand_cursor);
    }//GEN-LAST:event_show_donorMouseEntered

    private void delete_donorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_delete_donorMouseClicked
        
        this.setTitle("Delete Donor");
        
        // To change the background color of selected panels
       
        deleteDonar_panel.setBackground(new Color(153, 0, 51));
        
        profile_panel.setBackground(new Color(51, 51, 51));
        showDonar_panel.setBackground(new Color(51, 51, 51));
        showVisitor_panel.setBackground(new Color(51, 51, 51));
        showMessage_panel.setBackground(new Color(51, 51, 51));
        
        // add DeleteDonar_panel to dynamicPanel of Admin Frame
        
        dynamicPanel.removeAll();
        dynamicPanel.add(panel3);
        dynamicPanel.repaint();
        dynamicPanel.revalidate();
    }//GEN-LAST:event_delete_donorMouseClicked

    private void delete_donorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_delete_donorMouseEntered
        
        delete_donor.setCursor(hand_cursor);
    }//GEN-LAST:event_delete_donorMouseEntered

    private void show_visitorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_show_visitorMouseClicked
        
        this.setTitle("Show Visitor");
        
        // To change the background color of selected panels
       
        showVisitor_panel.setBackground(new Color(153, 0, 51));
        
        profile_panel.setBackground(new Color(51, 51, 51));
        showDonar_panel.setBackground(new Color(51, 51, 51));
        deleteDonar_panel.setBackground(new Color(51, 51, 51));
        showMessage_panel.setBackground(new Color(51, 51, 51));
        
        // add ShowVisitor_panel to dynamicPanel of Admin Frame
        
        dynamicPanel.removeAll();
        dynamicPanel.add(panel4);
        dynamicPanel.repaint();
        dynamicPanel.revalidate();
    }//GEN-LAST:event_show_visitorMouseClicked

    private void show_visitorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_show_visitorMouseEntered
        
        show_visitor.setCursor(hand_cursor);
    }//GEN-LAST:event_show_visitorMouseEntered

    private void show_messageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_show_messageMouseClicked
       
        this.setTitle("Show Message");
        
        // To change the background color of selected panels
       
        showMessage_panel.setBackground(new Color(153, 0, 51));
        
        profile_panel.setBackground(new Color(51, 51, 51));
        showDonar_panel.setBackground(new Color(51, 51, 51));
        deleteDonar_panel.setBackground(new Color(51, 51, 51));
        showVisitor_panel.setBackground(new Color(51, 51, 51));
        
        // add ShowMessage_panel to dynamicPanel of Admin Frame
        
        dynamicPanel.removeAll();
        dynamicPanel.add(panel5);
        dynamicPanel.repaint();
        dynamicPanel.revalidate();
    }//GEN-LAST:event_show_messageMouseClicked

    private void show_messageMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_show_messageMouseEntered
        
        show_message.setCursor(hand_cursor);
    }//GEN-LAST:event_show_messageMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel close;
    private javax.swing.JPanel deleteDonar_panel;
    private javax.swing.JLabel delete_donor;
    private javax.swing.JPanel dynamicPanel;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel minimize;
    private javax.swing.JLabel profile;
    private javax.swing.JPanel profile_panel;
    private javax.swing.JPanel showDonar_panel;
    private javax.swing.JPanel showMessage_panel;
    private javax.swing.JPanel showVisitor_panel;
    private javax.swing.JLabel show_donor;
    private javax.swing.JLabel show_message;
    private javax.swing.JLabel show_visitor;
    // End of variables declaration//GEN-END:variables
}
