
package mangement;

import java.awt.Color;
import java.awt.Cursor;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import mangement.panel.ChangePassword_panel;
import mangement.panel.Delete_panel;
import mangement.panel.EditProfile_panel;
import mangement.panel.Profile_panel;
import mangement.panel.Request_for_Blood;

public class Donor_Profile extends javax.swing.JFrame {
    
    Cursor cursor;
    private ImageIcon icon;
    
    // Object of Panels 
    
    Profile_panel panel1 = new Profile_panel();
    EditProfile_panel panel2 = new EditProfile_panel();
    ChangePassword_panel panel3 = new ChangePassword_panel();
    Request_for_Blood panel4 = new Request_for_Blood();
    Delete_panel panel5 = new Delete_panel();

    /**
     * Creates new form Donar_Profile
     */
    public Donor_Profile() {
        initComponents();
        
        this.setBounds(200,90,1020, 620);
        this.setResizable(false);
        this.setTitle("Profile");
        
        icon = new ImageIcon(getClass().getResource("Blood logo.png"));
        this.setIconImage(icon.getImage());
        
        cursor = new Cursor(Cursor.HAND_CURSOR);
        
        multiPanel.add(panel1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        minimize = new javax.swing.JLabel();
        close = new javax.swing.JLabel();
        display = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        password_panel = new javax.swing.JPanel();
        changePassword = new javax.swing.JLabel();
        editProfile_panel = new javax.swing.JPanel();
        editProfile = new javax.swing.JLabel();
        profile_panel = new javax.swing.JPanel();
        profile = new javax.swing.JLabel();
        request_blood_Panel = new javax.swing.JPanel();
        showRequest = new javax.swing.JLabel();
        delete_panel = new javax.swing.JPanel();
        deleteAccount = new javax.swing.JLabel();
        multiPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(88, 67, 85));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        minimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/homeIcon/icons8_Minimize_Window_20px.png"))); // NOI18N
        minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                minimizeMouseEntered(evt);
            }
        });
        jPanel1.add(minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 0, 20, 40));

        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/homeIcon/icons8_Cancel_20px.png"))); // NOI18N
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeMouseEntered(evt);
            }
        });
        jPanel1.add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 0, 30, 40));

        display.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        display.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(display, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 450, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 40));

        jPanel2.setBackground(new java.awt.Color(101, 79, 161));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        password_panel.setBackground(new java.awt.Color(101, 79, 161));
        password_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        changePassword.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        changePassword.setForeground(new java.awt.Color(255, 255, 255));
        changePassword.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        changePassword.setText("Change Password");
        changePassword.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        changePassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                changePasswordMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                changePasswordMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                changePasswordMouseExited(evt);
            }
        });
        password_panel.add(changePassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 130, 40));

        jPanel2.add(password_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 0, 150, 40));

        editProfile_panel.setBackground(new java.awt.Color(101, 79, 161));
        editProfile_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        editProfile.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        editProfile.setForeground(new java.awt.Color(255, 255, 255));
        editProfile.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        editProfile.setText("Edit Profile ");
        editProfile.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        editProfile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editProfileMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                editProfileMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                editProfileMouseExited(evt);
            }
        });
        editProfile_panel.add(editProfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 120, 40));

        jPanel2.add(editProfile_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 110, 40));

        profile_panel.setBackground(new java.awt.Color(204, 51, 0));
        profile_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        profile.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        profile.setForeground(new java.awt.Color(255, 255, 255));
        profile.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        profile.setText("Profile ");
        profile.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        profile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                profileMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                profileMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                profileMouseExited(evt);
            }
        });
        profile_panel.add(profile, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 40));

        jPanel2.add(profile_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 120, 40));

        request_blood_Panel.setBackground(new java.awt.Color(101, 79, 161));
        request_blood_Panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        showRequest.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        showRequest.setForeground(new java.awt.Color(255, 255, 255));
        showRequest.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        showRequest.setText("Request for Blood");
        showRequest.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        showRequest.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showRequestMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                showRequestMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                showRequestMouseExited(evt);
            }
        });
        request_blood_Panel.add(showRequest, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 40));

        jPanel2.add(request_blood_Panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 0, 160, 40));

        delete_panel.setBackground(new java.awt.Color(101, 79, 161));
        delete_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        deleteAccount.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        deleteAccount.setForeground(new java.awt.Color(255, 255, 255));
        deleteAccount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        deleteAccount.setText("Delete Account ");
        deleteAccount.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        deleteAccount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteAccountMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                deleteAccountMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                deleteAccountMouseExited(evt);
            }
        });
        delete_panel.add(deleteAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 118, 40));

        jPanel2.add(delete_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 0, 120, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 1020, 40));

        multiPanel.setLayout(new java.awt.CardLayout());
        getContentPane().add(multiPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 1020, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void profileMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profileMouseEntered

        profile.setCursor(cursor);

    }//GEN-LAST:event_profileMouseEntered

    private void profileMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profileMouseExited

    }//GEN-LAST:event_profileMouseExited

    private void editProfileMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editProfileMouseEntered

        editProfile.setCursor(cursor);
    }//GEN-LAST:event_editProfileMouseEntered

    private void editProfileMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editProfileMouseExited

    }//GEN-LAST:event_editProfileMouseExited

    private void changePasswordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_changePasswordMouseEntered

        changePassword.setCursor(cursor);

    }//GEN-LAST:event_changePasswordMouseEntered

    private void changePasswordMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_changePasswordMouseExited
           
    }//GEN-LAST:event_changePasswordMouseExited

    private void showRequestMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showRequestMouseEntered

        showRequest.setCursor(cursor);
    }//GEN-LAST:event_showRequestMouseEntered

    private void showRequestMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showRequestMouseExited

    }//GEN-LAST:event_showRequestMouseExited

    private void deleteAccountMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteAccountMouseEntered

        deleteAccount.setCursor(cursor);
    }//GEN-LAST:event_deleteAccountMouseEntered

    private void deleteAccountMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteAccountMouseExited


    }//GEN-LAST:event_deleteAccountMouseExited

    private void minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseClicked

        this.setState(this.ICONIFIED);
    }//GEN-LAST:event_minimizeMouseClicked

    private void minimizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseEntered

        minimize.setToolTipText("minimize");
        minimize.setCursor(cursor);
    }//GEN-LAST:event_minimizeMouseEntered

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked

        int choice = JOptionPane.showConfirmDialog(null, "Are you sure to exit ?", "Close", JOptionPane.YES_NO_OPTION,JOptionPane.PLAIN_MESSAGE);

        if (choice==JOptionPane.YES_OPTION){

            dispose();      // close the current window
        }
    }//GEN-LAST:event_closeMouseClicked

    private void closeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseEntered

        close.setCursor(cursor);
        close.setToolTipText("close");
    }//GEN-LAST:event_closeMouseEntered

    private void profileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profileMouseClicked
        
        this.setTitle("Profile");
        
        // To change color of selected panel
        
        profile_panel.setBackground(new Color(204, 51, 0));
        
        // change the other color of panels
        
        editProfile_panel.setBackground(new Color(101, 79, 161));
        password_panel.setBackground(new Color(101, 79, 161));
        request_blood_Panel.setBackground(new Color(101, 79, 161));
        delete_panel.setBackground(new Color(101, 79, 161));
        
        // Add Profile_panel
        
        multiPanel.removeAll();
        multiPanel.add(panel1);
        multiPanel.repaint();
        multiPanel.revalidate();
        
        
        
        
    }//GEN-LAST:event_profileMouseClicked

    private void editProfileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editProfileMouseClicked
        
        this.setTitle("Edit Profile");
        
        // To change color of selected panel
        
        editProfile_panel.setBackground(new Color(204, 51, 0));
        
        // change the other color of panels
        
        profile_panel.setBackground(new Color(101, 79, 161));
        password_panel.setBackground(new Color(101, 79, 161));
        request_blood_Panel.setBackground(new Color(101, 79, 161));
        delete_panel.setBackground(new Color(101, 79, 161));
        
        // Add Profile_panel
        
        multiPanel.removeAll();
        multiPanel.add(panel2);
        multiPanel.repaint();
        multiPanel.revalidate();
    }//GEN-LAST:event_editProfileMouseClicked

    private void changePasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_changePasswordMouseClicked
        
        this.setTitle("Change Password");
        
        // To change color of selected panel
        
        password_panel.setBackground(new Color(204, 51, 0));
        
        // change the other color of panels
        
        profile_panel.setBackground(new Color(101, 79, 161));
        editProfile_panel.setBackground(new Color(101, 79, 161));
        request_blood_Panel.setBackground(new Color(101, 79, 161));
        delete_panel.setBackground(new Color(101, 79, 161));
        
        // Add Profile_panel
        
        multiPanel.removeAll();
        multiPanel.add(panel3);
        multiPanel.repaint();
        multiPanel.revalidate();
        
    }//GEN-LAST:event_changePasswordMouseClicked

    private void deleteAccountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteAccountMouseClicked
        
        this.setTitle("Delete Account");
        
        // To change color of selected panel
        
        delete_panel.setBackground(new Color(204, 51, 0));
        
        // change the other color of panels
        
        profile_panel.setBackground(new Color(101, 79, 161));
        editProfile_panel.setBackground(new Color(101, 79, 161));
        request_blood_Panel.setBackground(new Color(101, 79, 161));
        password_panel.setBackground(new Color(101, 79, 161));
        
        // Add Profile_panel
        
        multiPanel.removeAll();
        multiPanel.add(panel5);
        multiPanel.repaint();
        multiPanel.revalidate();
    }//GEN-LAST:event_deleteAccountMouseClicked

    private void showRequestMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showRequestMouseClicked
        
        this.setTitle("Request for  Blood");
        
        // To change color of selected panel
        
        request_blood_Panel.setBackground(new Color(204, 51, 0));
        
        // change the other color of panels
        
        profile_panel.setBackground(new Color(101, 79, 161));
        editProfile_panel.setBackground(new Color(101, 79, 161));
        delete_panel.setBackground(new Color(101, 79, 161));
        password_panel.setBackground(new Color(101, 79, 161));
        
        // Add Profile_panel
        
        multiPanel.removeAll();
        multiPanel.add(panel4);
        multiPanel.repaint();
        multiPanel.revalidate();
    }//GEN-LAST:event_showRequestMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Donor_Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Donor_Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Donor_Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Donor_Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Donor_Profile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel changePassword;
    private javax.swing.JLabel close;
    private javax.swing.JLabel deleteAccount;
    private javax.swing.JPanel delete_panel;
    private javax.swing.JLabel display;
    private javax.swing.JLabel editProfile;
    private javax.swing.JPanel editProfile_panel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel minimize;
    private javax.swing.JPanel multiPanel;
    private javax.swing.JPanel password_panel;
    private javax.swing.JLabel profile;
    private javax.swing.JPanel profile_panel;
    private javax.swing.JPanel request_blood_Panel;
    private javax.swing.JLabel showRequest;
    // End of variables declaration//GEN-END:variables
}
