
package mangement;

import com.sun.glass.events.KeyEvent;
import java.awt.Color;
import java.awt.Cursor;
import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.ButtonGroup;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;


public class Donor_form extends javax.swing.JFrame {
    private Cursor cursor;
    private ImageIcon image;
    private ButtonGroup group;
    
    


    /**
     * Creates new form Registration_Form
     */
    public Donor_form() {
        initComponents();
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.setBounds(200,90,1018, 550);
        this.setResizable(false);
        this.setTitle("Registration Form");
        
        image = new ImageIcon(getClass().getResource("Blood logo.png"));   
        this.setIconImage(image.getImage());        // Change Icon of the Frame
        
        cursor = new Cursor(Cursor.HAND_CURSOR);    // create object of Cursor
        
        group = new ButtonGroup();      //create object of ButtonGroup
        
        group.add(male);
        group.add(female);       //add male and female button in same ButtonGroup
        
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jOptionPane1 = new javax.swing.JOptionPane();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jSeparator11 = new javax.swing.JSeparator();
        jSeparator12 = new javax.swing.JSeparator();
        jSeparator13 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        phoneNumber = new javax.swing.JTextField();
        age = new javax.swing.JTextField();
        lastName = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        password2 = new javax.swing.JPasswordField();
        password = new javax.swing.JPasswordField();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        location = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        firstName = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        bloodGroup = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        beDonor = new javax.swing.JButton();
        member = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        jSeparator14 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        contractNumber = new javax.swing.JTextField();
        female = new javax.swing.JRadioButton();
        male = new javax.swing.JRadioButton();
        close = new javax.swing.JLabel();
        minimize = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 0, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Donate Blood Save Life");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, -1, 60));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Peoples.png"))); // NOI18N
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, 152, 171));
        jPanel1.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 300, 10));
        jPanel1.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 380, 230, 10));
        jPanel1.add(jSeparator13, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 400, 120, 10));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Donate Blood_1.png"))); // NOI18N
        jLabel13.setToolTipText("");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 110, 72));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 550));

        jPanel2.setBackground(new java.awt.Color(0, 51, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(0, 51, 102));
        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Enter your Age");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 160, 30));

        jLabel2.setBackground(new java.awt.Color(0, 51, 102));
        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("First Name");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 147, 50));

        jLabel3.setBackground(new java.awt.Color(0, 51, 102));
        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Last Name");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 40, 140, 30));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 255));
        jLabel4.setText("( Enter 12 number )");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 130, 50));

        jLabel5.setBackground(new java.awt.Color(0, 51, 102));
        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Contract Number");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 190, 180, 30));

        jLabel6.setBackground(new java.awt.Color(0, 51, 102));
        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Retype Passowrd");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 160, 30));

        jLabel7.setBackground(new java.awt.Color(0, 51, 102));
        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Select your Blood Group");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 110, 180, 30));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 250, 230, 10));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 250, 10));

        phoneNumber.setBackground(new java.awt.Color(0, 51, 102));
        phoneNumber.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        phoneNumber.setForeground(new java.awt.Color(255, 255, 255));
        phoneNumber.setToolTipText("minimum 12 digit");
        phoneNumber.setBorder(null);
        jPanel2.add(phoneNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 300, 30));

        age.setBackground(new java.awt.Color(0, 51, 102));
        age.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        age.setForeground(new java.awt.Color(255, 255, 255));
        age.setBorder(null);
        age.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ageKeyTyped(evt);
            }
        });
        jPanel2.add(age, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, 200, 30));

        lastName.setBackground(new java.awt.Color(0, 51, 102));
        lastName.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lastName.setForeground(new java.awt.Color(255, 255, 255));
        lastName.setBorder(null);
        jPanel2.add(lastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 70, 240, 30));
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 190, 140, 0));

        password2.setBackground(new java.awt.Color(0, 51, 102));
        password2.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        password2.setForeground(new java.awt.Color(255, 255, 255));
        password2.setBorder(null);
        jPanel2.add(password2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 200, 30));

        password.setBackground(new java.awt.Color(0, 51, 102));
        password.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        password.setForeground(new java.awt.Color(255, 255, 255));
        password.setBorder(null);
        jPanel2.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 200, 30));
        jPanel2.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 390, 250, 10));
        jPanel2.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 200, 10));

        location.setBackground(new java.awt.Color(0, 51, 102));
        location.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        location.setForeground(new java.awt.Color(255, 255, 255));
        location.setBorder(null);
        jPanel2.add(location, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 360, 250, 30));
        jPanel2.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 100, 240, 10));

        firstName.setBackground(new java.awt.Color(0, 51, 102));
        firstName.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        firstName.setForeground(new java.awt.Color(255, 255, 255));
        firstName.setBorder(null);
        jPanel2.add(firstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 250, 30));
        jPanel2.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, 200, 10));

        bloodGroup.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        bloodGroup.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "O (+)", "A(+)", "B(+)", "AB(+)", "O(-)", "A(-)", "B(-)", "AB(-)", " " }));
        bloodGroup.setBorder(null);
        jPanel2.add(bloodGroup, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 150, 140, 30));

        jLabel8.setBackground(new java.awt.Color(0, 51, 102));
        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Location");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 330, 160, 30));
        jPanel2.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 460, 180, 10));

        beDonor.setBackground(new java.awt.Color(255, 255, 255));
        beDonor.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        beDonor.setForeground(new java.awt.Color(0, 0, 51));
        beDonor.setText("Be Donor");
        beDonor.setBorder(null);
        beDonor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                beDonorMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                beDonorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                beDonorMouseExited(evt);
            }
        });
        jPanel2.add(beDonor, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 420, 130, 40));

        member.setBackground(new java.awt.Color(0, 51, 102));
        member.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        member.setForeground(new java.awt.Color(255, 255, 255));
        member.setText("Already Member !");
        member.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                memberMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                memberMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                memberMouseExited(evt);
            }
        });
        jPanel2.add(member, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 410, 170, 50));
        jPanel2.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, 200, 10));
        jPanel2.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 390, 250, 10));
        jPanel2.add(jSeparator14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 300, 10));

        jLabel12.setBackground(new java.awt.Color(0, 51, 102));
        jLabel12.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Password");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 160, 30));

        contractNumber.setBackground(new java.awt.Color(0, 51, 102));
        contractNumber.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        contractNumber.setForeground(new java.awt.Color(255, 255, 255));
        contractNumber.setBorder(null);
        jPanel2.add(contractNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 220, 230, 30));

        female.setBackground(new java.awt.Color(0, 51, 102));
        female.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        female.setForeground(new java.awt.Color(255, 255, 255));
        female.setText("Female");
        jPanel2.add(female, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 280, 90, -1));

        male.setBackground(new java.awt.Color(0, 51, 102));
        male.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        male.setForeground(new java.awt.Color(255, 255, 255));
        male.setText("Male");
        jPanel2.add(male, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 280, 90, -1));

        close.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/homeIcon/icons8_Cancel_20px.png"))); // NOI18N
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeMouseEntered(evt);
            }
        });
        jPanel2.add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 0, 30, 40));

        minimize.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        minimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/homeIcon/icons8_Minimize_Window_20px.png"))); // NOI18N
        minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                minimizeMouseEntered(evt);
            }
        });
        jPanel2.add(minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 0, 30, 40));

        jLabel9.setBackground(new java.awt.Color(0, 51, 102));
        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Phone Number ");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 110, 50));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, 670, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    // To check all the feilds
    
    private boolean validateField(){
        
        String pass = password.getText();
        
        if (firstName.getText().isEmpty() || lastName.getText().isEmpty() || phoneNumber.getText().isEmpty() 
                || password.getText().isEmpty() || password2.getText().isEmpty() || contractNumber.getText().isEmpty()
                || age.getText().isEmpty() || location.getText().isEmpty() ||!password2.getText().equals(pass)){
            
            JOptionPane.showMessageDialog(null, "Please Fill up all Requirements Correctly","Warning",JOptionPane.PLAIN_MESSAGE);
            
            return false;
        }
        
        return true;
    }
    
    private void beDonorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_beDonorMouseEntered
        beDonor.setBackground(Color.GREEN);
        beDonor.setForeground(Color.WHITE);
        beDonor.setCursor(cursor);
    }//GEN-LAST:event_beDonorMouseEntered

    private void beDonorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_beDonorMouseExited
        beDonor.setBackground(Color.WHITE);
        beDonor.setForeground(new Color(0,0,51));
        
    }//GEN-LAST:event_beDonorMouseExited

    private void memberMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_memberMouseEntered
        
        member.setForeground(Color.orange);
        member.setCursor(cursor);
    }//GEN-LAST:event_memberMouseEntered

    private void memberMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_memberMouseExited
        member.setForeground(Color.WHITE);
    }//GEN-LAST:event_memberMouseExited

    private void memberMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_memberMouseClicked
        
        dispose();
        
        Log_In login = new Log_In();
        login.setVisible(true);
    }//GEN-LAST:event_memberMouseClicked

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        
        int choice = JOptionPane.showConfirmDialog(null, "Are you sure to exit ?", "Close", JOptionPane.YES_NO_OPTION,JOptionPane.PLAIN_MESSAGE);
        
        if (choice==JOptionPane.YES_OPTION){
            
           dispose();      // close the window
        }
    }//GEN-LAST:event_closeMouseClicked

    private void closeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseEntered
       
        close.setCursor(cursor);
        close.setToolTipText("close");
    }//GEN-LAST:event_closeMouseEntered

    private void minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseClicked
        
        this.setState(this.ICONIFIED);
    }//GEN-LAST:event_minimizeMouseClicked

    private void minimizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseEntered
        
        minimize.setToolTipText("minimize");
        minimize.setCursor(cursor);
    }//GEN-LAST:event_minimizeMouseEntered

    private void beDonorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_beDonorMouseClicked
        
        
       if (validateField()){

      
           try
            {
                Connection conn= MySqlConnect.ConnectDB();
                String sql="INSERT INTO blood_management_system.donar_information(firstName,lastName,phoneNumber,password,age,bloodGroup,anotherContactNumber,gender,location) value (?,?,?,?,?,?,?,?,?)";
                PreparedStatement  pst=conn.prepareStatement(sql);
                pst.setString(1,firstName.getText());
                pst.setString(2,lastName.getText());
                pst.setString(3, phoneNumber.getText());
                pst.setString(4,password.getText());
                pst.setInt(5,Integer.parseInt(age.getText()));
              
                String bloodgroup;
                
                bloodgroup = bloodGroup.getSelectedItem().toString();
                pst.setString(6,bloodgroup);
              
              
                pst.setString(7, contractNumber.getText());
                
                String gender = null;
                
                if(male.isSelected()){
                    
                    gender = male.getText();
                }
                if (female.isSelected()){
                    
                    gender = female.getText();
                }  
                pst.setString(8, gender);
                pst.setString(9, location.getText());
               
                 
                pst.execute();
                 
                 JOptionPane.showMessageDialog(null, "Registration successfull","Success",JOptionPane.PLAIN_MESSAGE);
                 conn.close();
                 dispose();
       
       }
       catch(Exception e)
       {
         
            JOptionPane.showMessageDialog(null, "Registration Failed","ERROR",JOptionPane.PLAIN_MESSAGE);
           
            }
       }
    }//GEN-LAST:event_beDonorMouseClicked

    private void ageKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ageKeyTyped
        
        char c = evt.getKeyChar();
        
        if (!(Character.isDigit(c) || (c==KeyEvent.VK_BACKSPACE) ||(c==KeyEvent.VK_DELETE))){
            
            getToolkit().beep();
            evt.consume();
        }

        
    }//GEN-LAST:event_ageKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Donor_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Donor_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Donor_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Donor_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Donor_form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField age;
    private javax.swing.JButton beDonor;
    private javax.swing.JComboBox<String> bloodGroup;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel close;
    private javax.swing.JTextField contractNumber;
    private javax.swing.JRadioButton female;
    private javax.swing.JTextField firstName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTextField lastName;
    private javax.swing.JTextField location;
    private javax.swing.JRadioButton male;
    private javax.swing.JLabel member;
    private javax.swing.JLabel minimize;
    private javax.swing.JPasswordField password;
    private javax.swing.JPasswordField password2;
    private javax.swing.JTextField phoneNumber;
    // End of variables declaration//GEN-END:variables
}
