/*
 * 
**************************************************************
***   Author       : Md.Touhidul Islam Shawan              ***                                             
***   Email        : touhidulislamshawan@gmail.com         ***                                                 
***   University   : Daffodil International University     ***                                                   
***   Department   : Computer Science and Engineering      ***                                                    
***   Facebook     : www.facebook.com/touhidulshawan       ***                                                
***   Contact      : 01689352421                           ***                                                 
**************************************************************
 */

package mangement.panelAdmin;

/**
 *
 * @author shawan
 */

import com.sun.glass.events.KeyEvent;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Image;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import mangement.MySqlConnect;

public class DeleteDonor_panel extends javax.swing.JPanel {
    
    private Cursor handCursor;

    /**
     * Creates new form DeleteDonar_panel
     */
    public DeleteDonor_panel() {
        initComponents();
        
        handCursor = new Cursor(Cursor.HAND_CURSOR);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        account_number = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        delete = new javax.swing.JButton();
        show = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        data_table = new javax.swing.JTable();

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(1, 133, 116));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(0, 0, 51));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Enter 12 digit number of Donor ");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 300, 39));

        account_number.setBackground(new java.awt.Color(1, 133, 116));
        account_number.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        account_number.setForeground(new java.awt.Color(255, 255, 255));
        account_number.setBorder(null);
        account_number.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                account_numberKeyPressed(evt);
            }
        });
        jPanel3.add(account_number, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 300, 30));
        jPanel3.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 300, 10));

        delete.setBackground(new java.awt.Color(255, 255, 255));
        delete.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        delete.setForeground(new java.awt.Color(0, 0, 51));
        delete.setText("Delete ");
        delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                deleteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                deleteMouseExited(evt);
            }
        });
        jPanel3.add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, 120, 40));

        show.setBackground(new java.awt.Color(255, 255, 255));
        show.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        show.setForeground(new java.awt.Color(0, 0, 51));
        show.setText("Show");
        show.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                showMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                showMouseExited(evt);
            }
        });
        jPanel3.add(show, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 120, 40));

        data_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "First Name", "Last Name", "Phone Number", "Blood Group"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(data_table);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 40, 620, 420));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 590));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

     private boolean validateField(){
        
        if (account_number.getText().isEmpty()){
            
            JOptionPane.showMessageDialog(null, "Please enter your 12 digit number","Warning",JOptionPane.PLAIN_MESSAGE);
            
            return false;
        }
        
        return true;
    }
    
    private void deleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteMouseClicked

        if (validateField()){

            try  {

                Connection conn = MySqlConnect.ConnectDB();
                String query = "DELETE FROM blood_management_system.donar_information WHERE phoneNumber = '"+account_number.getText()+"'";
                PreparedStatement pst = conn.prepareStatement(query);

                pst.executeUpdate();
                JOptionPane.showMessageDialog(null, "Delete Successfully","Success",JOptionPane.PLAIN_MESSAGE);

            }catch (Exception e){

                /* IGNORE */
            }
        }

    }//GEN-LAST:event_deleteMouseClicked

    private void deleteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteMouseEntered

        delete.setCursor(handCursor);
        delete.setBackground(Color.RED);
        delete.setForeground(Color.white);

    }//GEN-LAST:event_deleteMouseEntered

    private void deleteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteMouseExited
        delete.setBackground(Color.WHITE);
        delete.setForeground(new Color(0, 0, 51));
    }//GEN-LAST:event_deleteMouseExited

    private void showMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showMouseClicked
        if (validateField()){
        
            try {
            
            java.sql.Connection conn = MySqlConnect.ConnectDB();
            String query = "SELECT * FROM blood_management_system.donar_information WHERE phoneNumber = '"+account_number.getText()+"'";
            
            PreparedStatement pst = conn.prepareStatement(query);
            ResultSet rs = pst.executeQuery();
            
            DefaultTableModel table = (DefaultTableModel)data_table.getModel();
            table.setRowCount(0);
            
            while(rs.next()){
                
                Object obj[] = {rs.getString("firstName"),rs.getString("lastName"),rs.getString("phoneNumber"),
                    rs.getString("bloodGroup")};
                
                table.addRow(obj);
                
            }
            
            
            
        }catch(Exception e){
            
            JOptionPane.showMessageDialog(null, "Something error","Not found",JOptionPane.PLAIN_MESSAGE);
        }
            
        }      
    }//GEN-LAST:event_showMouseClicked

    private void showMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showMouseEntered
        
        show.setBackground(new Color(41, 39, 40));
        show.setForeground(Color.WHITE);
        show.setCursor(handCursor);
    }//GEN-LAST:event_showMouseEntered

    private void showMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showMouseExited
        
        show.setBackground(Color.WHITE);
        show.setForeground(new Color(0,0,51));
    }//GEN-LAST:event_showMouseExited

    private void account_numberKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_account_numberKeyPressed
        
        if (evt.getKeyCode()==KeyEvent.VK_ENTER){
            
            
        }
    }//GEN-LAST:event_account_numberKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField account_number;
    private javax.swing.JTable data_table;
    private javax.swing.JButton delete;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JButton show;
    // End of variables declaration//GEN-END:variables
}
