/*
 * 
**************************************************************
***   Author       : Md.Touhidul Islam Shawan              ***                                             
***   Email        : touhidulislamshawan@gmail.com         ***                                                 
***   University   : Daffodil International University     ***                                                   
***   Department   : Computer Science and Engineering      ***                                                    
***   Facebook     : www.facebook.com/touhidulshawan       ***                                                
***   Contact      : 01778669104                           ***                                                 
**************************************************************
 */
package mangement.panelAdmin;

import java.awt.Cursor;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import static javax.swing.UIManager.getString;
import javax.swing.table.DefaultTableModel;
import mangement.MySqlConnect;

public class ShowDonor_panel extends javax.swing.JPanel {
    
    private Cursor cursor;

    /**
     * Creates new form ShowDonar_panel
     */
    public ShowDonor_panel() {
        initComponents();
        cursor = new Cursor(Cursor.HAND_CURSOR);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        view = new javax.swing.JLabel();
        bloodGroup = new javax.swing.JComboBox<>();
        showDonar = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        data_table = new javax.swing.JTable();

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(101, 79, 161));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        view.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        view.setForeground(new java.awt.Color(255, 255, 255));
        view.setText("View all Donor`s Profile Data");
        view.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                viewMouseEntered(evt);
            }
        });
        jPanel2.add(view, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 11, 264, 38));

        bloodGroup.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bloodGroup.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A (+)", "A (-)", "B (+)", "B (-)", "AB (+)", "AB (-)", "O (+)", "O (-)" }));
        jPanel2.add(bloodGroup, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 150, 190, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 60));

        showDonar.setBackground(new java.awt.Color(101, 79, 161));
        showDonar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        data_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "First Name", "Last Name", "Phone Number", "Password ", "Age ", "Blood Group", "Another Contact Number", "Gender", "Location"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(data_table);

        jScrollPane2.setViewportView(jScrollPane1);

        showDonar.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 540));

        jPanel1.add(showDonar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 1100, 540));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void viewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewMouseClicked
        
        
        try {
            
            Connection conn = MySqlConnect.ConnectDB();
            String query = "SELECT * FROM blood_management_system.donar_information";
            
            PreparedStatement pst = conn.prepareStatement(query);
            ResultSet rs = pst.executeQuery();
            
            DefaultTableModel table = (DefaultTableModel)data_table.getModel();
            table.setRowCount(0);
            
            while(rs.next()){
                
                Object obj[] = {rs.getString("firstName"),rs.getString("lastName"),rs.getString("phoneNumber"),
                    rs.getString("password"),rs.getInt("age"),rs.getString("bloodGroup"),rs.getString("anotherContactNumber"),
                    rs.getString("gender"),rs.getString("location")};
                
                table.addRow(obj);
            }
            conn.close();
            
        }catch(Exception e){
            
            JOptionPane.showMessageDialog(null, "Something error","Not found",JOptionPane.PLAIN_MESSAGE);
            
        }
        
        
    }//GEN-LAST:event_viewMouseClicked

    private void viewMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewMouseEntered
        
        view.setCursor(cursor);
    }//GEN-LAST:event_viewMouseEntered


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> bloodGroup;
    private javax.swing.JTable data_table;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel showDonar;
    private javax.swing.JLabel view;
    // End of variables declaration//GEN-END:variables
}
